# Generated by Django 2.1.2 on 2018-11-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='escription',
        ),
    ]
