# Generated by Django 2.1.2 on 2018-11-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20181124_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='escription',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
