# Generated by Django 2.1.2 on 2018-11-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_photos/default.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
