# Generated by Django 2.1.2 on 2018-11-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseturl',
            name='user',
        ),
        migrations.DeleteModel(
            name='ResetURL',
        ),
    ]
