# Generated by Django 2.1.2 on 2018-11-30 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181128_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.TextField(default=''),
        ),
    ]
