# Generated by Django 2.1.2 on 2018-11-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181120_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(default='', max_length=150)),
                ('latitude', models.FloatField(default=0.0, max_length=150)),
                ('longitude', models.FloatField(default=0.0, max_length=150)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('rsvp_list', models.ManyToManyField(blank=True, to='pages.Profile')),
            ],
        ),
    ]
