# Generated by Django 2.1.2 on 2018-10-23 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_auto_20181022_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userBlocked', to=settings.AUTH_USER_MODEL)),
                ('userBlocking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userBlocking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userFollowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='userFollowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userFollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
