# Generated by Django 2.1.2 on 2018-10-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20181027_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profile_photos/default.jpg', null=True, upload_to='profile_photos/'),
        ),
    ]
