# Generated by Django 2.1.2 on 2018-10-19 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageContent', models.TextField()),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postContent', models.TextField()),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=75)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('age', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='userOne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userOne', to='pages.User'),
        ),
        migrations.AddField(
            model_name='thread',
            name='userTwo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTwo', to='pages.User'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Thread'),
        ),
        migrations.AddField(
            model_name='follow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='pages.User'),
        ),
        migrations.AddField(
            model_name='follow',
            name='userFollowing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFollowing', to='pages.User'),
        ),
    ]
