# Generated by Django 2.1.2 on 2018-10-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181019_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='isRequest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='isRequest',
            field=models.BooleanField(default=False),
        ),
    ]
